language: go

go:
  - "1.14"

os:
  - linux

git:
  depth: 1
  quiet: true
  submodules: false

notifications:
  email: false

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"

before_install:
  - echo "current branch is ${BRANCH}"

stages:
  - name: Tests

jobs:
  include:
    - stage: "Tests"
      name: "Makefile"
      install:
        - go mod download
        - go install github.com/golangci/golangci-lint/cmd/golangci-lint
      script:
        - make lint
        - make test
        - make integration-tests

