version: '3.7'

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - tests/database.env

  migration:
    build:
      context: .
      dockerfile: tests/migration.dockerfile
    depends_on:
      - postgres
    command: sh -c 'dockerize -wait tcp://postgres:5432 -- /go/bin/goose -dir /app/migrations postgres "host=postgres port=5432 user=calljournal password=calljournal dbname=calljournal sslmode=disable" up && sleep 30'

  calljournal:
    build:
      context: .
      dockerfile: tests/calljournal.dockerfile
    ports:
      - 9111:9111
    depends_on:
      - postgres
      - migration
    env_file:
      - tests/calljournal.env
    environment:
      - CJ_DB_HOST=postgres
    command: sh -c 'dockerize -wait tcp://postgres:5432 -- /go/bin/calljournal'

  calluploader:
    build:
      context: .
      dockerfile: tests/calluploader.dockerfile
    depends_on:
      - calljournal
    env_file:
      - tests/calluploader.env
    environment:
      - CJ_GRPC_SERVER_ADDR=calljournal:9111
    command: sh -c 'dockerize -wait tcp://calljournal:9111 -- /go/bin/calluploader'



