version: '3.7'

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: calljournal
      POSTGRES_PASSWORD: calljournal
      POSTGRES_DB: calljournal

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: calljournal
      MINIO_SECRET_KEY: calljournal
    command: server /data

  nsqd:
    image: nsqio/nsq
    hostname: "nsqdservice"
    ports:
      - 4150:4150
      - 4151:4151
    command: /nsqd
