version: '3.7'

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=calljournal
      - POSTGRES_PASSWORD=calljournal
      - POSTGRES_DB=calljournal

  migration:
    build:
      context: .
      dockerfile: tests/migration.dockerfile
    depends_on:
      - postgres
    command: sh -c 'dockerize -wait tcp://postgres:5432 -- /go/bin/goose -dir /app/migrations postgres "host=postgres port=5432 user=calljournal password=calljournal dbname=calljournal sslmode=disable" up && sleep 60'

  nsqd:
    image: nsqio/nsq
    ports:
      - 4150:4150
      - 4151:4151
    command: /nsqd -msg-timeout=30m -max-msg-timeout=45m

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=calljournal
      - MINIO_SECRET_KEY=calljournal
    command: server /data

  cdrserver:
    build:
      context: .
      dockerfile: tests/cdrserver.dockerfile
    ports:
      - 9111:9111
      - 41010:41010
    depends_on:
      - migration
      - nsqd
    env_file:
      - tests/cdrserver.env
    environment:
      - CJ_NSQD_ADDR=nsqd:4150
    command: sh -c 'dockerize -wait tcp://nsqd:4150 -- /go/bin/cdrserver'

  cdrclient:
    build:
      context: .
      dockerfile: tests/cdrclient.dockerfile
    ports:
      - 41011:41011
    depends_on:
      - cdrserver
    env_file:
      - tests/cdrclient.env
    environment:
      - CJ_GRPC_SERVER_ADDR=cdrserver:9111
    command: sh -c 'dockerize -wait tcp://cdrserver:9111 -- /go/bin/cdrclient'

  cdrstore:
    build:
      context: .
      dockerfile: tests/cdrstore.dockerfile
    depends_on:
      - postgres
      - cdrserver
      - migration
      - nsqd
    env_file:
      - tests/cdrstore.env
    environment:
      - CJ_DB_HOST=postgres
      - CJ_DB_PORT=5432
      - CJ_NSQD_ADDR=nsqd:4150
      - CJ_GRPC_SERVER_ADDR=cdrserver:9111
      - CJ_MINIO_ENDPOINT=minio:9000
    command: sh -c 'dockerize -wait tcp://nsqd:4150 -wait tcp://postgres:5432 --wait tcp://minio:9000 -- /go/bin/cdrstore'

  integration_tests:
    build:
      context: .
      dockerfile: tests/integration_tests.dockerfile
    depends_on:
      - postgres
      - migration
      - cdrserver
      - cdrclient
    env_file:
      - tests/cdrstore.env
    environment:
      - CJ_DB_HOST=postgres
      - CJ_DB_PORT=5432
      - CJ_MINIO_ENDPOINT=minio:9000
    command: sh -c 'dockerize -wait tcp://postgres:5432 --wait tcp://minio:9000 -- go test -v -tags integration ./tests/cj_test.go'

